server:
  port: 8007

spring:
  cloud:
    stream:
      bindings:
        s2-input-channel:
          destination: pca-submeter-2
        mapping-input-channel:
          destination: pca-mappings
        s2-output-channel:
          destination: pca-submeter-output
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              commit.interval.ms: 10000
              state.dir: state-store
          bindings:
            s2-input-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            mapping-input-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                materializedAs: mappings-store
            s2-output-channel:
              producer:
                producer:
                  valueSerde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde



application:
  configs:
    error.topic.name: error-topic
